---
##
# MySQL DB dumping.
#
#
- name: Installs backup script
  template:
    src: backup_all_databases.j2
    dest: /usr/local/bin/database_backup
    mode: 0700
    owner: root
    group: root

- name: Ensure gpg is installed
  apt:
    pkg: gpg
    state: present

- name: Import public gpg keys
  shell: "curl -s {{ item.url }} | gpg --import --trust-model always -"
  changed_when: '"imported" in __mariadb_gpgkeys.stderr'
  register: __mariadb_gpgkeys
  loop: "{{ mariadb_backup_gpg_keys }}"
  tags: keys

- name: Ensures backup destination exists
  file:
    path: "{{ mariadb_backup_destination }}"
    state: directory
    mode: 0700
    owner: root

- name: Ensures encrypted backup destination exists
  file:
    path: "{{ mariadb_backup_destination }}/gpg"
    state: directory
    mode: 0700
    owner: root

- name: Add cron entry
  template:
    src: cron.j2
    dest: /etc/cron.d/database_backup
    owner: root
    group: root
    mode: 0600
  tags:
    - cron

- name: Add logrotate entry
  ansible.builtin.template:
    src: logrotate_backup.j2
    dest: /etc/logrotate.d/database_backup
    owner: root
    group: root
    mode: 0644
  tags:
    - logrotate
