---
##
# MySQL DB dumping.
#
#
- name: Installs backup script
  template:
    src: "../templates/backup_all_databases.j2"
    dest: /etc/backup.d/hourly/20_backup_all_mysql_databases.sh
    mode: 0700

- 
- name: Ensures backup destination exists
  file:
    path: "{{ mariadb_backup_destination }}"
    state: directory
    mode: 0700
    owner: root

- name: Remove old backup method crontab entry
  file:
    path: /etc/cron.d/backup_all_databases
    state: 'absent'
