---
##
# mariadb database setup.
#
#

- name: Installs mariadb-server
  apt:
    pkg: "mariadb-server-{{ mariadb_version }}"
    state: present

- name: Installs additional tools
  apt:
    pkg: "{{ mariadb_additional_tools }}"
    state: present

- name: Adds mysql config
  template:
    src: my.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-ansible.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mariadb
  tags:
    - mariadb:config

- name: Creates data directory
  file:
    state: directory
    path: "{{ mariadb_data_dir }}"
    owner: mysql
    group: mysql
    mode: 0755
  notify: Restart mariadb
  register: __new_datadir
  tags:
    - mariadb:config

- name: Stop mysql if datadir is new
  service:
    name: mariadb
    state: stopped
  when: __new_datadir is changed

- name: Initialize datadir if new
  command: >
    /usr/bin/mysql_install_db --datadir={{ mariadb_data_dir }} 
    --auth-root-authentication-method=socket
    --rpm --cross-bootstrap --user=mysql
    --disable-log-bin  --skip-test-db
  when: __new_datadir is changed

- name: Restart mariadb if necessary
  meta: flush_handlers

- name: Adds Python2 MySQL support
  apt:
    pkg: "python-mysqldb"
    state: present
  when: ansible_facts.python.version.major == 2

- name: Adds Python3 MySQL support
  apt:
    pkg: "python3-mysqldb"
    state: present
  when: ansible_facts.python.version.major == 3

# # In this case, mysql_user will fail connecting to mysql
- name: Sets the root password (first attempt / failure is ok)
  mysql_user:
    user: root
    password: "{{ mariadb_root_password }}"
    host: localhost

- name: Configures for easy access as root user
  template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600

# - name: Sets the root password (second attempt)
#   mysql_user:
#     user: root
#     password: "{{ mariadb_root_password }}"
#     host: localhost
#   ignore_errors: yes

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    state: "absent"

- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: "absent"

- name: Adds required MySQL users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.privs }}"
  with_items: [ "{{ mariadb_users }}" ]
  when: inventory_hostname == group_name[0]

- name: Adds required MySQL users with hosts
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.privs }}"
    host: "{{ item.host }}"
  with_items: [ "{{ mariadb_users }}" ]
  when: item.host is defined and mariadb_users is defined and inventory_hostname == group_name[0]

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    name: "root"
    password: "{{ mariadb_root_password }}"
    host: "::1"
  when: inventory_hostname == group_name[0]

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    name: "root"
    password: "{{ mariadb_root_password }}"
    host: "127.0.0.1"
  when: inventory_hostname == group_name[0]

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user:
    name: "root"
    password: "{{ mariadb_root_password }}"
    host: "localhost"
  when: inventory_hostname == group_name[0]

- name: Secures the MySQL root user for server_hostname domain
  mysql_user:
    name: "root"
    password: "{{ mariadb_root_password }}"
    host: "{{ ansible_fqdn }}"
  failed_when: false
  when: inventory_hostname == group_name[0]

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
  when: inventory_hostname == group_name[0]

- name: Adds ferm filtering
  template:
    src: ferm.j2
    dest: /etc/ferm/filter-input.d/60_mysql.conf
    mode: 0644
    owner: root
    group: root
  when: mariadb_ferm_enabled
  tags: ferm
  notify: Restart ferm
