---
- name: Creates monitoring user
  mysql_user:
    name: "{{ mariadb_monitoring_user }}"
    password: "{{ mariadb_monitoring_password }}"
    priv: '*.*:PROCESS/*.*:REPLICATION CLIENT/performance_schema.*:SELECT'
    host: "{{ item }}"
    state: present
  with_items:
    - localhost
    - 127.0.0.1
