---
- name: Restart mariadb
  ansible.builtin.service:
    name: mysql
    state: restarted
  when: mariadb_skip_restart is not defined or not mariadb_skip_restart

- name: Restart ferm
  ansible.builtin.service:
    name: ferm
    state: restarted

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
