---
- name: Restart mariadb
  service:
   name: mysql
   state: restarted

- name: Restart ferm
  service:
   name: ferm
   state: restarted

- name: Reload nftables service
  systemd:
    name: nftables
    state: restarted